export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_FAIL_HANDLE = 'AUTH_FAIL_HANDLE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


export const ME_START = 'SET_ME_START';
export const ME_SUCCESS = 'SET_ME_SUCCESS';
export const ME_ERROR = 'SET_ME_ERROR';
export const SET_LANDING_REDIRECT_PATH = 'SET_LANDING_PATH_REDIRECT_PATH';



export const SHIPMENT_GET_START = 'SHIPMENT_GET_START';
export const SHIPMENT_GET_SUCCESS = 'SHIPMENT_GET_SUCCESS';
export const SHIPMENT_GET_FAIL = 'SHIPMENT_GET_FAIL';
