export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_FAIL_HANDLE = 'AUTH_FAIL_HANDLE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const ME_START = 'SET_ME_START';
export const ME_SUCCESS = 'SET_ME_SUCCESS';
export const ME_ERROR = 'SET_ME_ERROR';
export const SET_LANDING_REDIRECT_PATH = 'SET_LANDING_PATH_REDIRECT_PATH';


//ORDER ACTIONS
export const ORDER_GET_START = 'GET_ORDER_START';
export const ORDER_GET_SUCCESS = 'GET_ORDER_SUCCESS';
export const ORDER_GET_FAIL = 'GET_ORDER_FAIL';
export const ORDER_GET_FAIL_HANDLE = 'GET_ORDER_FAIL_HANDLE';
export const ORDER_GET_STATUS_START = 'GET_ORDER_STATUS_START';
export const ORDER_GET_STATUS_SUCESS = 'GET_ORDER_STATUS_SUCESS';
export const ORDER_GET_STATUS_FAIL = 'GET_ORDER_STATUS_FAIL';
export const ORDER_GET_STATUS_FAIL_HANDLE = 'GET_ORDER_STATUS_FAIL_HANDLE';
export const ORDER_GET_COMPONENTS_START = 'GET_ORDER_COMPONENTS_START';
export const ORDER_GET_COMPONENTS_SUCCESS = 'GET_ORDER_COMPONENTS_SUCESS';
export const ORDER_GET_COMPONENTS_FAIL = 'GET_ORDER_COMPONENTS_FAIL';
export const ORDER_GET_COMPONENTS_FAIL_HANDLE = 'GET_ORDER_COMPONENTS_FAIL_HANDLE';
export const ORDER_GET_PAGINATION_START = 'GET_ORDER_PAGINATION_START';
export const ORDER_GET_PAGINATION_SUCCESS = 'GET_ORDER_PAGINATION_SUCCESS';
export const ORDER_GET_PAGINATION_FAIL = 'GET_ORDER_PAGINATION_FAIL';
export const ORDER_GET_PAGINATION_FAIL_HANDLE = 'GET_ORDER_PAGINATION_FAIL_HANDLE';

export const SHIPMENT_GET_START = 'SHIPMENT_GET_START';
export const SHIPMENT_GET_SUCCESS = 'SHIPMENT_GET_SUCCESS';
export const SHIPMENT_GET_FAIL = 'SHIPMENT_GET_FAIL';

//ALERT ACTIONS
export const ALERT_GET_START = 'ALERT_GET_START';
export const ALERT_GET_SUCCESS = 'ALERT_GET_SUCCESS';
export const ALERT_GET_FAIL = 'ALERT_GET_FAIL';
